export const ActionTypes = {
  BLOG_DATA: "BLOG_DATA",
  LOADING: "LOADING",
  INDIVIDUAL_BLOG_DATA: "INDIVIDUAL_BLOG_DATA",
  GET_MY_BLOGS: "GET_MY_BLOGS",
  GET_USER_DETAILS: "GET_USER_DETAILS",
};
